"""foreblocks.modules.heads.

Package initializer that exposes the public symbols for this namespace.
It belongs to the forecasting head composition and projection modules area of Foreblocks.

"""

from foreblocks.modules.heads.config import (
    AlignmentMode,
    HeadComposerConfig,
    HeadNASConfig,
    NASMode,
    ParallelFusion,
    ParallelStageConfig,
    SerialMerge,
    SerialStageConfig,
    StageKind,
    StructuredOutputPolicy,
)
from foreblocks.modules.heads.contracts import HeadOutput, HeadShape
from foreblocks.modules.heads.graph import HeadGraph, HeadGraphState, HeadStage
from foreblocks.modules.heads.head_helper import HeadComposer, HeadSpec
from foreblocks.modules.heads.heads import (
    DAIN,
    Chronos2EmbedHead,
    DAINHead,
    DecompositionBlock,
    DecompositionHead,
    Differencing,
    DifferencingHead,
    DropoutTSHead,
    FFTTopK,
    FFTTopKHead,
    HaarWaveletTopK,
    HaarWaveletTopKHead,
    LearnableFourierSeasonal,
    LearnableFourierSeasonalHead,
    MultiKernelConvHead,
    MultiScaleConv,
    MultiScaleConvHead,
    PatchEmbed,
    PatchEmbedHead,
    RevIN,
    RevINHead,
    Time2Vec,
    Time2VecHead,
    TimeAttention,
    TimeAttentionHead,
)

__all__ = [
    "DAIN",
    "AlignmentMode",
    "Chronos2EmbedHead",
    "DAINHead",
    "DecompositionBlock",
    "DecompositionHead",
    "Differencing",
    "DifferencingHead",
    "DropoutTSHead",
    "FFTTopK",
    "FFTTopKHead",
    "HaarWaveletTopK",
    "HaarWaveletTopKHead",
    "HeadComposer",
    "HeadComposerConfig",
    "HeadGraph",
    "HeadGraphState",
    "HeadNASConfig",
    "HeadOutput",
    "HeadShape",
    "HeadSpec",
    "HeadStage",
    "LearnableFourierSeasonal",
    "LearnableFourierSeasonalHead",
    "MultiKernelConvHead",
    "MultiScaleConv",
    "MultiScaleConvHead",
    "NASMode",
    "ParallelFusion",
    "ParallelStageConfig",
    "PatchEmbed",
    "PatchEmbedHead",
    "RevIN",
    "RevINHead",
    "SerialMerge",
    "SerialStageConfig",
    "StageKind",
    "StructuredOutputPolicy",
    "Time2Vec",
    "Time2VecHead",
    "TimeAttention",
    "TimeAttentionHead",
]
