# server.py — async streaming execution

import asyncio
import base64
import io
import json
import os
import re
import time
import traceback
import uuid
from concurrent.futures import Future, ThreadPoolExecutor
from contextlib import asynccontextmanager  # noqa: E402
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
import uvicorn
from fastapi import APIRouter, FastAPI, HTTPException, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

# ──────────────────────────────────────────────────────────────────────────────
# Settings
# ──────────────────────────────────────────────────────────────────────────────
MAX_WORKERS = max(2, os.cpu_count() or 2)
ARTIFACTS_DIR = os.path.abspath("./artifacts")
os.makedirs(ARTIFACTS_DIR, exist_ok=True)
DIST_DIR = Path(os.getenv("DIST_DIR", "dist")).resolve()
INDEX_HTML = DIST_DIR / "index.html"


# ──────────────────────────────────────────────────────────────────────────────
# JSON-safe conversion helpers
# ──────────────────────────────────────────────────────────────────────────────
def _json_safe(value: Any) -> Any:
    """Best-effort conversion to JSON-serializable Python primitives."""
    if value is None or isinstance(value, (str, int, float, bool)):
        return value

    # Torch tensors
    if torch.is_tensor(value):
        if value.numel() == 1:
            try:
                return _json_safe(value.item())
            except Exception:
                return str(value)
        try:
            return value.detach().cpu().tolist()
        except Exception:
            return str(value)

    # NumPy-like scalars/arrays and other objects exposing item()/tolist()
    if hasattr(value, "item") and callable(getattr(value, "item")):
        try:
            return _json_safe(value.item())
        except Exception:
            pass
    if hasattr(value, "tolist") and callable(getattr(value, "tolist")):
        try:
            return _json_safe(value.tolist())
        except Exception:
            pass

    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(v) for v in value]

    # Final fallback to string
    return str(value)


# ──────────────────────────────────────────────────────────────────────────────
# Models
# ──────────────────────────────────────────────────────────────────────────────
class ExecuteRequest(BaseModel):
    code: str = Field(..., description="Python code generated by the frontend")
    workflow: Dict[str, Any] = Field(..., description="{nodes, connections}")
    sync: bool = Field(False, description="If true, wait and return results inline")
    timeout_sec: float = Field(1.5, description="Max time to wait when sync=True")


class ExecuteResponse(BaseModel):
    success: bool
    task_id: str
    results: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


class StatusResponse(BaseModel):
    task_id: str
    state: str
    progress: float
    message: str
    results: Optional[Dict[str, Any]] = None


@dataclass
class TaskRecord:
    task_id: str
    state: str = "queued"
    progress: float = 0.0
    message: str = ""
    results: Dict[str, Any] = field(default_factory=dict)
    started_at: float = field(default_factory=time.time)
    finished_at: Optional[float] = None
    future: Optional[Future] = None
    logs: List[str] = field(default_factory=list)
    artifacts: List[str] = field(default_factory=list)


# ──────────────────────────────────────────────────────────────────────────────
# Task Manager
# ──────────────────────────────────────────────────────────────────────────────
class TaskManager:
    def __init__(self):
        self.pool = ThreadPoolExecutor(
            max_workers=MAX_WORKERS, thread_name_prefix="ts-worker"
        )
        self.tasks: Dict[str, TaskRecord] = {}
        self.ws_clients: Dict[str, List[WebSocket]] = {}
        self.loop: Optional[asyncio.AbstractEventLoop] = None  # set on startup

    def create(self) -> TaskRecord:
        tid = str(uuid.uuid4())
        rec = TaskRecord(task_id=tid)
        self.tasks[tid] = rec
        self.ws_clients[tid] = []
        return rec

    def get(self, task_id: str) -> TaskRecord:
        rec = self.tasks.get(task_id)
        if not rec:
            raise KeyError(f"Task {task_id} not found")
        return rec

    async def attach_ws(self, task_id: str, ws: WebSocket):
        await ws.accept()
        if task_id not in self.ws_clients:
            self.ws_clients[task_id] = []
        self.ws_clients[task_id].append(ws)

    async def detach_ws(self, task_id: str, ws: WebSocket):
        if task_id in self.ws_clients and ws in self.ws_clients[task_id]:
            self.ws_clients[task_id].remove(ws)

    async def notify(self, task_id: str, event: Dict[str, Any]):
        """Send to all connected clients for this task."""
        safe_event = _json_safe(event)
        for ws in list(self.ws_clients.get(task_id, [])):
            try:
                await ws.send_text(json.dumps(safe_event))
            except Exception:
                try:
                    await self.detach_ws(task_id, ws)
                except Exception:
                    pass

    def notify_threadsafe(self, task_id: str, event: Dict[str, Any]):
        """Schedule a notify from any thread."""
        if self.loop is None:
            return
        asyncio.run_coroutine_threadsafe(self.notify(task_id, event), self.loop)

    def submit(self, rec: TaskRecord, func, *args, **kwargs):
        future = self.pool.submit(func, rec.task_id, *args, **kwargs)
        rec.future = future
        return future


MANAGER = TaskManager()


# ──────────────────────────────────────────────────────────────────────────────
# Utility
# ──────────────────────────────────────────────────────────────────────────────
def pick_output_node_id(workflow: Dict[str, Any]) -> Optional[str]:
    try:
        for n in workflow.get("nodes", []):
            if str(n.get("type")) == "output":
                return n.get("id")
    except Exception:
        pass
    return None


def _log(task_id: str, msg: str):
    rec = MANAGER.get(task_id)
    stamp = time.strftime("%H:%M:%S")
    line = f"[{stamp}] ({task_id[:8]}) {msg}"
    rec.logs.append(line)
    print(line, flush=True)


# ──────────────────────────────────────────────────────────────────────────────
# Report Bridge (pushes live WS events)
# ──────────────────────────────────────────────────────────────────────────────
class ReportBridge:
    """
    API exposed to user code via 'report'.
    Use:
      report.log("message")
      report.progress(0.5, "halfway")
      report.set_result(node_id, 'metrics', {...})
      report.artifact("plot.png", fig_or_bytes_or_path)
    """

    def __init__(self, task_id: str):
        self.task_id = task_id

    def log(self, text: str):
        _log(self.task_id, text)
        MANAGER.notify_threadsafe(self.task_id, {"event": "log", "line": text})

    def progress(self, value: float, message: str = ""):
        rec = MANAGER.get(self.task_id)
        rec.progress = max(0.0, min(1.0, float(value)))
        if message:
            rec.message = message
        _log(self.task_id, f"progress={rec.progress:.0%} {message}".strip())
        MANAGER.notify_threadsafe(
            self.task_id,
            {
                "event": "state",
                "state": rec.state,
                "progress": rec.progress,
                "message": rec.message,
            },
        )

    def set_result(self, node_id: str, result_type: str, data: Any):
        """
        result_type: 'plot' | 'image' | 'metrics' | 'table' | 'json' | 'array' | 'text'
        """
        import matplotlib.pyplot as plt

        rec = MANAGER.get(self.task_id)
        # Images / plots
        if result_type in ("plot", "image"):
            if hasattr(data, "savefig"):  # matplotlib figure
                buf = io.BytesIO()
                data.savefig(buf, format="png", bbox_inches="tight")
                plt.close(data)
                buf.seek(0)
                encoded = base64.b64encode(buf.read()).decode("utf-8")
                rec.results[node_id] = {"type": "plot", "data": encoded}
            elif isinstance(data, (bytes, bytearray)):
                encoded = base64.b64encode(bytes(data)).decode("utf-8")
                rec.results[node_id] = {"type": "image", "data": encoded}
            else:
                rec.results[node_id] = {"type": "text", "data": str(data)}
        elif result_type == "metrics":
            clean = {}
            if isinstance(data, dict):
                for k, v in data.items():
                    try:
                        if hasattr(v, "item"):
                            v = v.item()
                        if isinstance(v, (int, float)):
                            v = float(v)
                    except Exception:
                        pass
                    clean[str(k)] = v
                rec.results[node_id] = {"type": "metrics", "data": clean}
            else:
                rec.results[node_id] = {"type": "text", "data": str(data)}
        elif result_type == "table":
            if isinstance(data, dict) and "columns" in data and "rows" in data:
                rec.results[node_id] = {"type": "table", "data": data}
            else:
                rec.results[node_id] = {"type": "text", "data": str(data)}
        elif result_type == "json":
            try:
                json.dumps(data)
                rec.results[node_id] = {"type": "json", "data": data}
            except Exception:
                rec.results[node_id] = {"type": "text", "data": str(data)}
        elif result_type == "array":
            if hasattr(data, "tolist"):
                rec.results[node_id] = {"type": "array", "data": data.tolist()}
            elif isinstance(data, (list, tuple)):
                rec.results[node_id] = {"type": "array", "data": list(data)}
            else:
                rec.results[node_id] = {"type": "text", "data": str(data)}
        else:
            rec.results[node_id] = {"type": "text", "data": str(data)}

        _log(self.task_id, f"📊 Result set for node {node_id} (type: {result_type})")
        MANAGER.notify_threadsafe(
            self.task_id,
            {
                "event": "node_result",
                "node_id": node_id,
                "result": rec.results[node_id],
            },
        )

    def artifact(self, name: str, data: Any):
        """Save an artifact file under ./artifacts/<task>_<name>"""
        import shutil

        path = os.path.join(ARTIFACTS_DIR, f"{self.task_id}_{name}")
        if isinstance(data, (bytes, bytearray)):
            with open(path, "wb") as f:
                f.write(data)
        elif isinstance(data, str) and os.path.exists(data):
            shutil.copyfile(data, path)
        else:
            try:
                import matplotlib.pyplot as plt

                fig = data
                buf = io.BytesIO()
                fig.savefig(buf, format="png", bbox_inches="tight")
                with open(path, "wb") as f:
                    f.write(buf.getvalue())
                plt.close(fig)
            except Exception:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(str(data))
        rec = MANAGER.get(self.task_id)
        rec.artifacts.append(os.path.basename(path))
        _log(self.task_id, f"📁 artifact saved: {os.path.basename(path)}")
        MANAGER.notify_threadsafe(
            self.task_id, {"event": "artifact", "name": os.path.basename(path)}
        )


# ──────────────────────────────────────────────────────────────────────────────
# Worker
# ──────────────────────────────────────────────────────────────────────────────
def _run_user_code(task_id: str, code: str, workflow: Dict[str, Any]):
    """Execute user code with enhanced result handling."""
    rec = MANAGER.get(task_id)
    rec.state = "running"
    rec.progress = 0.02
    rec.message = "Starting execution"
    MANAGER.notify_threadsafe(
        task_id,
        {
            "event": "state",
            "state": rec.state,
            "progress": rec.progress,
            "message": rec.message,
        },
    )
    _log(task_id, "⏳ Starting execution")

    # Non-interactive matplotlib
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np  # noqa

    report = ReportBridge(task_id)

    glb = {
        "__name__": "__main__",
        "__package__": None,
        "torch": torch,
        "report": report,
    }
    loc: Dict[str, Any] = {}

    try:
        _log(task_id, "📜 Executing generated code...")
        rec.message = "Executing generated code"
        rec.progress = 0.12
        MANAGER.notify_threadsafe(
            task_id,
            {
                "event": "state",
                "state": rec.state,
                "progress": rec.progress,
                "message": rec.message,
            },
        )
        print(code)
        exec(code, glb, loc)  # user code
        _log(task_id, "✓ Code executed successfully")

        # If user code didn’t set results, try to infer something useful.
        if not rec.results:
            _log(task_id, "No explicit results set, attempting auto-detection...")
            trainer = loc.get("trainer")
            X_val, Y_val = loc.get("X_val"), loc.get("Y_val")
            time_series = loc.get("time_series", None)
            offset = loc.get("train_size", None)

            metrics = loc.get("metrics")
            if (
                metrics is None
                and trainer
                and (X_val is not None)
                and (Y_val is not None)
            ):
                _log(task_id, "🧮 Computing metrics via trainer.metrics(...)")
                rec.message = "Computing metrics"
                rec.progress = 0.35
                MANAGER.notify_threadsafe(
                    task_id,
                    {
                        "event": "state",
                        "state": rec.state,
                        "progress": rec.progress,
                        "message": rec.message,
                    },
                )
                try:
                    metrics = trainer.metrics(X_val, Y_val)
                except Exception as e:
                    _log(task_id, f"⚠️ metrics() failed: {e}")
                    metrics = None

            plot_b64 = None
            try:
                if trainer and (X_val is not None) and (Y_val is not None):
                    _log(task_id, "📈 Generating plot via trainer.plot_prediction(...)")
                    rec.message = "Generating plot"
                    rec.progress = 0.55
                    MANAGER.notify_threadsafe(
                        task_id,
                        {
                            "event": "state",
                            "state": rec.state,
                            "progress": rec.progress,
                            "message": rec.message,
                        },
                    )
                    fig = trainer.plot_prediction(
                        X_val,
                        Y_val,
                        full_series=time_series if time_series is not None else None,
                        offset=int(offset) if offset is not None else 0,
                        show=False,
                    )
                    buf = io.BytesIO()
                    fig.savefig(buf, format="png", bbox_inches="tight")
                    plt.close(fig)
                    buf.seek(0)
                    plot_b64 = base64.b64encode(buf.read()).decode("utf-8")
            except Exception as e:
                _log(task_id, f"⚠️ plot failed: {e}")

            out_id = pick_output_node_id(workflow) or "output_1"
            if metrics is not None:
                rec.results[out_id] = {"type": "metrics", "data": _json_safe(metrics)}
                MANAGER.notify_threadsafe(
                    task_id,
                    {
                        "event": "node_result",
                        "node_id": out_id,
                        "result": rec.results[out_id],
                    },
                )
            if plot_b64 is not None:
                plot_id = out_id if metrics is None else f"{out_id}_plot"
                rec.results[plot_id] = {"type": "plot", "data": plot_b64}
                MANAGER.notify_threadsafe(
                    task_id,
                    {
                        "event": "node_result",
                        "node_id": plot_id,
                        "result": rec.results[plot_id],
                    },
                )
            if not rec.results:
                rec.results[out_id] = {
                    "type": "text",
                    "data": "Execution finished (no results found).",
                }
                MANAGER.notify_threadsafe(
                    task_id,
                    {
                        "event": "node_result",
                        "node_id": out_id,
                        "result": rec.results[out_id],
                    },
                )

        rec.state = "success"
        rec.message = "Done"
        rec.progress = 1.0
        rec.finished_at = time.time()
        _log(task_id, f"✅ Finished with {len(rec.results)} result(s)")
        MANAGER.notify_threadsafe(
            task_id,
            {"event": "done", "success": True, "results": _json_safe(rec.results)},
        )
    except Exception as e:
        rec.state = "error"
        rec.message = str(e)
        rec.progress = 1.0
        rec.finished_at = time.time()
        tb = traceback.format_exc()
        _log(task_id, "❌ Error:\n" + tb)
        MANAGER.notify_threadsafe(
            task_id, {"event": "done", "success": False, "error": rec.message}
        )


# ──────────────────────────────────────────────────────────────────────────────
# FastAPI app
# ──────────────────────────────────────────────────────────────────────────────


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Set the manager loop on startup
    MANAGER.loop = asyncio.get_running_loop()
    yield
    # (no special shutdown actions required)


app = FastAPI(title="ForeBlocks Backend", version="1.0", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────────────
# Core REST endpoints
# ──────────────────────────────────────────────────────────────────────────────
@app.post("/execute", response_model=ExecuteResponse)
def execute(req: ExecuteRequest):
    rec = MANAGER.create()
    MANAGER.submit(rec, _run_user_code, req.code, req.workflow)

    # Return immediately in async mode
    if not req.sync:
        return ExecuteResponse(success=True, task_id=rec.task_id)

    # For sync=True, wait briefly up to timeout
    deadline = time.time() + float(req.timeout_sec)
    while time.time() < deadline:
        if rec.state in ("success", "error", "cancelled"):
            break
        time.sleep(0.05)

    if rec.state == "success":
        return ExecuteResponse(success=True, task_id=rec.task_id, results=rec.results)
    if rec.state == "error":
        return ExecuteResponse(success=False, task_id=rec.task_id, error=rec.message)
    # still running
    return ExecuteResponse(success=True, task_id=rec.task_id)


@app.get("/status/{task_id}", response_model=StatusResponse)
def status(task_id: str):
    try:
        rec = MANAGER.get(task_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")
    # Return partial results if any, even while running
    return StatusResponse(
        task_id=task_id,
        state=rec.state,
        progress=rec.progress,
        message=rec.message,
        results=_json_safe(rec.results) if rec.results else None,
    )


@app.get("/logs/{task_id}")
def logs(task_id: str):
    try:
        rec = MANAGER.get(task_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")
    return JSONResponse({"task_id": task_id, "logs": rec.logs})


@app.get("/artifact/{task_id}/{name}")
def artifact(task_id: str, name: str):
    try:
        rec = MANAGER.get(task_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")
    fname = f"{task_id}_{name}"
    full = os.path.join(ARTIFACTS_DIR, fname)
    if not os.path.exists(full):
        raise HTTPException(status_code=404, detail="Artifact not found")
    return FileResponse(full)


@app.websocket("/ws/{task_id}")
async def ws(task_id: str, websocket: WebSocket):
    try:
        await MANAGER.attach_ws(task_id, websocket)

        try:
            rec = MANAGER.get(task_id)
        except KeyError:
            await websocket.send_text(
                json.dumps({"event": "error", "message": "Task not found"})
            )
            await websocket.close()
            return

        # Initial snapshot
        await MANAGER.notify(
            task_id,
            {
                "event": "snapshot",
                "state": rec.state,
                "progress": rec.progress,
                "message": rec.message,
                "logs": rec.logs[-50:],
            },
        )

        last_len = len(rec.logs)

        # Passive ticker; pushes without needing client messages
        while True:
            await asyncio.sleep(0.2)

            # Stream new logs
            rec = MANAGER.get(task_id)
            if len(rec.logs) > last_len:
                await MANAGER.notify(
                    task_id, {"event": "logs", "lines": rec.logs[last_len:]}
                )
                last_len = len(rec.logs)

            # Heartbeat
            await MANAGER.notify(
                task_id,
                {
                    "event": "state",
                    "state": rec.state,
                    "progress": rec.progress,
                    "message": rec.message,
                },
            )

            if rec.state in ("success", "error", "cancelled"):
                await MANAGER.notify(
                    task_id,
                    {
                        "event": "done",
                        "success": rec.state == "success",
                        "results": rec.results if rec.state == "success" else None,
                        "error": rec.message if rec.state == "error" else None,
                    },
                )
                break

    except WebSocketDisconnect:
        await MANAGER.detach_ws(task_id, websocket)
    except Exception:
        await MANAGER.detach_ws(task_id, websocket)


@app.post("/cancel/{task_id}")
def cancel(task_id: str):
    try:
        rec = MANAGER.get(task_id)
    except KeyError:
        raise HTTPException(status_code=404, detail="Task not found")
    if rec.future and not rec.future.done():
        rec.state = "cancelled"
        rec.message = "Cancelled by user"
        rec.progress = 1.0
        rec.finished_at = time.time()
        _log(task_id, "🛑 Cancel requested")
        MANAGER.notify_threadsafe(
            task_id, {"event": "done", "success": False, "error": "Cancelled by user"}
        )
        return {"ok": True, "note": "Task flagged as cancelled"}
    return {"ok": False, "note": "Task already finished"}


# ──────────────────────────────────────────────────────────────────────────────
# API Router aliases
# ──────────────────────────────────────────────────────────────────────────────
api = APIRouter(prefix="/api")


@api.post("/execute", response_model=ExecuteResponse)
def execute_api(req: ExecuteRequest):
    return execute(req)


@api.get("/status/{task_id}", response_model=StatusResponse)
def status_api(task_id: str):
    return status(task_id)


@api.get("/logs/{task_id}")
def logs_api(task_id: str):
    return logs(task_id)


@api.get("/artifact/{task_id}/{name}")
def artifact_api(task_id: str, name: str):
    return artifact(task_id, name)


@api.post("/cancel/{task_id}")
def cancel_api(task_id: str):
    return cancel(task_id)


@api.websocket("/ws/{task_id}")
async def ws_api(task_id: str, websocket: WebSocket):
    await ws(task_id, websocket)


@api.get("/analyze-csv")
def analyze_csv(path: str):
    """
    Analyzes a CSV file and returns metadata (input_size, target column, etc.)
    for intelligent UI configuration.
    """
    from foreblocks.data.csv import CSVSource
    if not os.path.exists(path):
        # Check if it exists relative to the current dir or is absolute
        full_path = os.path.abspath(path)
        if not os.path.exists(full_path):
             raise HTTPException(status_code=404, detail=f"File not found: {path}")
    else:
        full_path = path

    try:
        source = CSVSource(file_path=full_path)
        info = source.load_and_analyze()
        return info
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ──────────────────────────────────────────────────────────────────────────────
# Node discovery endpoints you included
# ──────────────────────────────────────────────────────────────────────────────
from foreblocks.ui.discovery import categories_map, discover_nodes  # noqa


@app.get("/health")
def health():
    return {"ok": True}


NODE_DEFS_PATH = os.path.join(os.path.dirname(__file__), "nodeDefinitions.js")


def load_static_nodes() -> dict:
    """Parse nodeDefinitions.js (object literal) into a Python dict."""
    if not os.path.exists(NODE_DEFS_PATH):
        return {}
    with open(NODE_DEFS_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    match = re.search(r"const\s+NODE_TYPES\s*=\s*({[\s\S]*?});", content)
    if not match:
        print("[WARN] nodeDefinitions.js: No NODE_TYPES found.")
        return {}

    js_text = match.group(1)
    js_text = re.sub(r"//.*", "", js_text)
    js_text = re.sub(r"/\*.*?\*/", "", js_text, flags=re.S)
    js_text = re.sub(r"\s+", " ", js_text)
    js_text = re.sub(r"'", '"', js_text)
    js_text = re.sub(r"([{,]\s*)([a-zA-Z_][a-zA-Z0-9_-]*)\s*:", r'\1"\2":', js_text)
    js_text = re.sub(r",(\s*[}\]])", r"\1", js_text)

    try:
        return json.loads(js_text)
    except json.JSONDecodeError as e:
        debug_file = os.path.join(
            os.path.dirname(NODE_DEFS_PATH), "nodeDefinitions_debug.json"
        )
        with open(debug_file, "w", encoding="utf-8") as dbg:
            dbg.write(js_text)
        print(f"[ERROR] Could not parse nodeDefinitions.js: {e}")
        print(f"[DEBUG] Saved normalized version to {debug_file}")
        return {}


@app.get("/nodes")
def list_nodes():
    discovered = discover_nodes()
    static_nodes = load_static_nodes()
    all_nodes = {**discovered, **static_nodes}
    cats = categories_map(all_nodes)
    print(
        f"Discovered {len(discovered)} dynamic nodes + {len(static_nodes)} static nodes"
    )
    print(f"Total {len(all_nodes)} nodes in {len(cats)} categories")
    return {"nodes": all_nodes, "categories": cats}


app.include_router(api)


# ──────────────────────────────────────────────────────────────────────────────
# Static files & SPA
# ──────────────────────────────────────────────────────────────────────────────
app.mount("/assets", StaticFiles(directory=str(DIST_DIR / "assets")), name="assets")


@app.get("/")
def read_index():
    headers = {"Cache-Control": "no-cache, no-store, must-revalidate"}
    if not INDEX_HTML.exists():
        raise HTTPException(status_code=404, detail=f"{INDEX_HTML} not found")
    return FileResponse(str(INDEX_HTML), headers=headers)


@app.get("/{full_path:path}")
def spa_fallback(full_path: str):
    if full_path.startswith("api") or full_path.startswith("assets"):
        raise HTTPException(status_code=404)
    headers = {"Cache-Control": "no-cache, no-store, must-revalidate"}
    if not INDEX_HTML.exists():
        raise HTTPException(status_code=404, detail=f"{INDEX_HTML} not found")
    return FileResponse(str(INDEX_HTML), headers=headers)


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
