import { NodeData, Connection, NodeTypeMap } from "../types/types";
import { topoSort } from "./graph";
import { sanitizeIdent, varNameFor } from "./ids";
import { pickBindings } from "./bindings";

function pyLiteral(v: any): string {
    if (typeof v === "string") {
        const s = v.trim().toLowerCase();
        if (s === "true") return "True";
        if (s === "false") return "False";
        if (s === "null" || s === "none") return "None";
        return JSON.stringify(v);
    }
    if (v === null || v === undefined) return "None";
    if (typeof v === "boolean") return v ? "True" : "False";
    if (typeof v === "number") {
        if (Number.isFinite(v)) return String(v);
        if (Number.isNaN(v)) return "float('nan')";
        return v > 0 ? "float('inf')" : "float('-inf')";
    }
    if (Array.isArray(v)) return `[${v.map(pyLiteral).join(", ")}]`;
    if (typeof v === "object") {
        const entries = Object.entries(v).map(([k, val]) => `${JSON.stringify(k)}: ${pyLiteral(val)}`);
        return `{${entries.join(", ")}}`;
    }
    return "None";
}

function upsertKwarg(kwargs: string[], key: string, valueExpr: string): string[] {
    const next = [...kwargs];
    const idx = next.findIndex((k) => k.trim().startsWith(`${key}=`));
    const kv = `${key}=${valueExpr}`;
    if (idx >= 0) next[idx] = kv;
    else next.push(kv);
    return next;
}

export function generateCode(nodes: NodeData[], connections: Connection[], nodeTypes: NodeTypeMap) {
    const id2node = Object.fromEntries(nodes.map((n) => [n.id, n]));
    const order = topoSort(nodes, connections);
    const importSet = new Set<string>([
        "import torch",
        "import torch.nn as nn",
        "import numpy as np",
        "from torch.utils.data import DataLoader, TensorDataset",
        "import matplotlib.pyplot as plt",
    ]);
    const outVarByPort: Record<string, string> = {};
    const typeCounts: Record<string, number> = {};
    const varNameByNode: Record<string, string> = {};
    const lines: string[] = [];
    lines.push("# Auto-generated by Time Series Model Builder");
    lines.push("# Any node with py metadata in /nodes is handled automatically.\n");

    for (const n of nodes) {
        const def = nodeTypes[n.type] || {};
        const py = (def as any).py || {};
        (py.imports || []).forEach((i: string) => importSet.add(i));
        const hb = (n.config as any)?.head_blocks;
        if (n.type === "head_composer" && Array.isArray(hb) && hb.length > 0) {
            importSet.add("from foreblocks.core.heads.head_helper import HeadSpec");
        }
    }
    lines.push(...Array.from(importSet).sort(), "");

    const dataNode = nodes.find((n) => n.type === "data_input");
    const hasTargetLenVar = dataNode?.config?.target_len != null;
    if (dataNode) {
        const cfg = dataNode.config || {};
        if (cfg.seq_len != null) lines.push(`seq_len = ${cfg.seq_len}`);
        if (cfg.target_len != null) lines.push(`target_len = ${cfg.target_len}`);
        if (cfg.total_len != null) lines.push(`total_len = ${cfg.total_len}`);
        lines.push("");
        lines.push("# Synthetic time series (demo)");
        lines.push("time_series = np.sin(np.linspace(0, 30*np.pi, total_len)) + 0.1*np.random.randn(total_len)");
        lines.push("time_series = torch.tensor(time_series, dtype=torch.float32).unsqueeze(-1)");
        lines.push("");
        lines.push("def create_sliding_windows(series, input_len, output_len):");
        lines.push(" X, Y = [], []");
        lines.push(" for i in range(len(series) - input_len - output_len):");
        lines.push("   X.append(series[i:i+input_len])");
        lines.push("   Y.append(series[i+input_len:i+input_len+output_len])");
        lines.push(" return torch.stack(X), torch.stack(Y)");
        lines.push("X, Y = create_sliding_windows(time_series, seq_len, target_len)");
        lines.push("train_size = int(0.8 * len(X))");
        lines.push("X_train, Y_train = X[:train_size], Y[:train_size]");
        lines.push("X_val, Y_val = X[train_size:], Y[train_size:]");
        lines.push("");
    }

    for (const node of order) {
        const def = nodeTypes[node.type] || {};
        const py: any = (def as any).py || {};
        const ctor = py.ctor;
        const varPrefix = py.var_prefix || sanitizeIdent(node.type);
        typeCounts[node.type] = (typeCounts[node.type] || 0) + 1;
        const vname = varNameFor(
            node.type,
            typeCounts[node.type] > 1 ? typeCounts[node.type] : "",
            varPrefix
        );
        varNameByNode[node.id] = vname;

        lines.push(`# Node: ${def.name || node.type} (${node.id})`);
        if (!ctor) {
            lines.push(`# TODO: No 'py.ctor' for type '${node.type}'. Emitting placeholder.`);
            lines.push(`${sanitizeIdent(node.id)} = None`);
            const outs = (def as any).outputs || ["output"];
            (outs as string[]).forEach((port) => {
                outVarByPort[`${node.id}:${port}`] = sanitizeIdent(node.id);
            });
            outVarByPort[`${node.id}:*`] = sanitizeIdent(node.id);
            outVarByPort[node.id] = sanitizeIdent(node.id);
            lines.push("");
            continue;
        }

        const bindSpec = py.bind || {};
        const { args, kwargs } = pickBindings(bindSpec, {
            node,
            nodeTypes,
            connections,
            id2node: id2node as any,
            outVarByPort,
        });

        if (node.type === "head_composer") {
            const cfg = (node.config || {}) as any;
            const rawBlocks = Array.isArray(cfg.head_blocks) ? cfg.head_blocks : [];
            if (rawBlocks.length > 0) {
                const normalized = rawBlocks
                    .filter((b: any) => b && typeof b === "object")
                    .map((b: any, idx: number) => {
                        const headNodeId = String(b.head_node_id || "").trim();
                        const stage = b.stage === "parallel" ? "parallel" : "serial";
                        const combine = b.combine === "invert" || b.combine === "add" ? b.combine : "none";
                        const alphaMode = b.alpha_mode === "gate" || b.alpha_mode === "soft" ? b.alpha_mode : "off";
                        const alphaMix = b.alpha_mix_style === "residual" ? "residual" : "blend";
                        const name = String(
                            b.name || `${headNodeId || `head_${idx + 1}`}_${stage}`,
                        );
                        return {
                            headNodeId,
                            stage,
                            combine,
                            alphaMode,
                            alphaMix,
                            name,
                            addProject: b.add_project !== false,
                            alphaInit: typeof b.alpha_init === "number" ? b.alpha_init : 0,
                            alphaTrainable: b.alpha_trainable !== false,
                            weightCarry: b.weight_carry !== false,
                        };
                    })
                    .filter((b: any) => b.headNodeId.length > 0);

                const makeSpecExpr = (b: any) => {
                    const headVar = varNameByNode[b.headNodeId] || sanitizeIdent(b.headNodeId);
                    return `HeadSpec(head=${headVar}, name=${pyLiteral(b.name)}, combine=${pyLiteral(b.combine)}, add_project=${pyLiteral(b.addProject)}, alpha_mode=${pyLiteral(b.alphaMode)}, alpha_init=${pyLiteral(b.alphaInit)}, alpha_trainable=${pyLiteral(b.alphaTrainable)}, weight_carry=${pyLiteral(b.weightCarry)}, alpha_mix_style=${pyLiteral(b.alphaMix)})`;
                };

                const parallelSpecs = normalized.filter((b: any) => b.stage === "parallel");
                const serialSpecs = normalized.filter((b: any) => b.stage !== "parallel");
                let composerMode = cfg.composer_mode;
                if (!["serial", "parallel", "hybrid"].includes(String(composerMode))) {
                    if (parallelSpecs.length > 0 && serialSpecs.length > 0) composerMode = "hybrid";
                    else if (parallelSpecs.length > 0) composerMode = "parallel";
                    else composerMode = "serial";
                }

                let resolvedKwargs = [...kwargs];
                resolvedKwargs = resolvedKwargs.filter(
                    (x) => !x.trim().startsWith("specs=") && !x.trim().startsWith("parallel_specs=") && !x.trim().startsWith("serial_specs=") && !x.trim().startsWith("composer_mode="),
                );
                resolvedKwargs = upsertKwarg(resolvedKwargs, "composer_mode", pyLiteral(composerMode));

                if (composerMode === "serial") {
                    const specsExpr = `[${serialSpecs.map(makeSpecExpr).join(", ")}]`;
                    resolvedKwargs = upsertKwarg(resolvedKwargs, "specs", specsExpr);
                } else if (composerMode === "parallel") {
                    const specsExpr = `[${parallelSpecs.map(makeSpecExpr).join(", ")}]`;
                    resolvedKwargs = upsertKwarg(resolvedKwargs, "parallel_specs", specsExpr);
                } else {
                    const pExpr = `[${parallelSpecs.map(makeSpecExpr).join(", ")}]`;
                    const sExpr = `[${serialSpecs.map(makeSpecExpr).join(", ")}]`;
                    resolvedKwargs = upsertKwarg(resolvedKwargs, "parallel_specs", pExpr);
                    resolvedKwargs = upsertKwarg(resolvedKwargs, "serial_specs", sExpr);
                }

                const argStr = [...args, ...resolvedKwargs].filter(Boolean).join(", ");
                lines.push(`${vname} = ${ctor}(${argStr})`);
                const outs = (def as any).outputs || ["output"];
                (outs as string[]).forEach((port) => {
                    const map = (py.output_map && py.output_map[port]) || "@self";
                    if (map === "@self") outVarByPort[`${node.id}:${port}`] = vname;
                    else if (map.startsWith("@attr:"))
                        outVarByPort[`${node.id}:${port}`] = `${vname}.${(map.slice(6) || "").replace(/[^a-zA-Z0-9_]/g, "_")}`;
                    else outVarByPort[`${node.id}:${port}`] = map;
                });
                outVarByPort[`${node.id}:*`] = vname;
                outVarByPort[node.id] = vname;
                lines.push("");
                continue;
            }
        }

        let resolvedKwargs = [...kwargs];
        if (hasTargetLenVar && node.type === "transformer_decoder") {
            resolvedKwargs = upsertKwarg(resolvedKwargs, "label_len", "target_len // 2");
        }
        if (hasTargetLenVar && node.type === "forecasting_model") {
            resolvedKwargs = upsertKwarg(resolvedKwargs, "target_len", "target_len");
        }

        const argStr = [...args, ...resolvedKwargs].filter(Boolean).join(", ");
        lines.push(`${vname} = ${ctor}(${argStr})`);
        const outs = (def as any).outputs || ["output"];
        (outs as string[]).forEach((port) => {
            const map = (py.output_map && py.output_map[port]) || "@self";
            if (map === "@self") outVarByPort[`${node.id}:${port}`] = vname;
            else if (map.startsWith("@attr:"))
                outVarByPort[`${node.id}:${port}`] = `${vname}.${(map.slice(6) || "").replace(/[^a-zA-Z0-9_]/g, "_")}`;
            else outVarByPort[`${node.id}:${port}`] = map;
        });
        outVarByPort[`${node.id}:*`] = vname;
        outVarByPort[node.id] = vname;
        lines.push("");
    }

    const trainer = nodes.find(
        (n) => (nodeTypes[n.type] as any)?.py?.role === "trainer" || n.type === "trainer"
    );
    if (trainer) {
        const tvar = varNameByNode[trainer.id] || sanitizeIdent(trainer.id);
        lines.push("# (Optional) Demo training if trainer was constructed above");
        lines.push("# Make DataLoader if not provided by nodes");
        lines.push(`train_loader = DataLoader(TensorDataset(X_train, Y_train), batch_size=${(trainer.config as any)?.batch_size ?? 64}, shuffle=True)`);
        lines.push(`_ = getattr(${tvar}, 'train', lambda *a, **k: None)(train_loader, epochs=${(trainer.config as any)?.epochs ?? 5})`);
        lines.push("");
    }

    const outputNode = nodes.find((n) => n.type === "output");
    if (outputNode) {
        const plot = !!(outputNode.config as any)?.plot;
        const metrics = !!(outputNode.config as any)?.metrics;
        const anyTrainerVar = trainer ? varNameByNode[trainer.id] || sanitizeIdent(trainer.id) : null;
        if (plot && anyTrainerVar)
            lines.push(`${anyTrainerVar}.plot_prediction(X_val, Y_val, full_series=time_series, offset=train_size)`);
        if (metrics && anyTrainerVar)
            lines.push(`print(getattr(${anyTrainerVar}, 'metrics', lambda X, Y: {})(X_val, Y_val))`);
        lines.push("");
    }

    return lines.join("\n");
}
